---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mkr-gcloud-auto-retirement
commonLabels:
  app: mkr-gcloud-auto-retirement
secretGenerator:
  - files:
      - GCLOUD_PROJECT_ID=secret/GCLOUD_PROJECT_ID
      - MACKEREL_APIKEY=secret/MACKEREL_APIKEY
      - MACKEREL_HOST_ID=secret/MACKEREL_HOST_ID
      - MACKEREL_ROLE=secret/MACKEREL_ROLE
      - MACKEREL_SERVICE=secret/MACKEREL_SERVICE
      - gcloud_service_account_key.json=secret/gcloud_service_account_key.json
    name: mkr-gcloud-auto-retirement
    type: Opaque
resources:
  - ../base/
